spring:
  application:
    name: CrawlerFetcher

  fetcher:
    startUrls: https://www.zhihu.com/people/huang-liao-57,https://www.zhihu.com/people/gong-qing-tuan-zhong-yang-67,https://www.zhihu.com/people/cloudycity
    proxyUrl: http://127.0.0.1:5010/get/
    threadSize: 1000

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: rabbitmq
    password: rabbitmq

server:
  port: 8081